name: Long Running CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Long running step
        run: |
          echo "Starting long job..."
          sleep 600  # Sleep for 5 minutes
          echo "Job finished"
